### ISSUE TITLE
CIDetectorTypeText

### ISSUE THREAD

**Issue by ghost** [alexruperez/ARDetector#2]
Whats the status on "CIDetectorTypeText"? Have you been able to get it to work in any of the Xcode Beta's?

https://developer.apple.com/library/prerelease/ios/documentation/CoreImage/Reference/CIDetector_Ref/#//apple_ref/doc/constant_group/Detector_Types

**Comment by alexruperez** [comment]
Hi @pyraego, i get the "FKTextDetector not loaded" error.

[Here](https://gist.github.com/Koze/bc6aa304744dc243ad48) @Koze said "works on the device. I checked with iOS 9 β4 on iPhone 6 Plus."

**Comment by ghost** [comment]
I will give this a try. Thank you!
